export interface jornadas{
    key?:string,
    fecha:Date,
    casa:Boolean,
    titulo:string,
    equipo: string,
    titular1: string,
    titular2:string ,
    titular3:string ,
    titular4:string ,
    titular5: string,
    resultado1: Number,
    resultado2:Number ,
    resultado3:Number ,
    resultado4:Number ,
    resultado5: Number,
}